---
- name: Listen for events on a webhook from Zabbix
  hosts: all
  sources:
    - name: Listen for alerts from Zabbix
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Output Zabbix Information
      condition: event.meta is defined
      action:
        debug:
