---
- name: Create env
  hosts: localhost
  tasks:
    - name: Add hosts
      ansible.builtin.add_host:
        name: "{{ hosts_update }}"
        groups: redhat
      with_items: '{{ hosts_update.split() }}'

- name: Red Hat
  hosts: redhat
  become: true
  remote_user: root
  tasks:
    - name: install httpd
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: start
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
    - name: Create index.html
      ansible.builtin.copy:
        content: "{{ ansible_facts.fqdn }}"
        dest: /var/www/html/index.html
